[package]
name = "dx-app"
version = "0.1.14"
authors = ["Marcos Fernández <marcosfernandezperez9@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", branch = "main", features = ["router", "fullstack"] }

[features]
default = ["dioxus/web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
bundle = []

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[target.'cfg(target_os = "android")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
