[application]
name = "DXApp"

[web.app]
title = "DXApp"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.dxapp"
publisher = "MarckFp"
icon = [
    "assets/icons/favicon-16x16.png",
    "assets/icons/32x32.png",
    "assets/icons/128x128.png",
    "assets/icons/favicon.ico",
    "assets/icons/icon.ico",
    "assets/icons/icon.icns"
]
