[application]
name = "DXApp"
out_dir = "web"


[web.app]
title = "DXApp"
base_path = "dx-app"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.dxapp"
publisher = "MarckFp"
icon = ["assets/icons/icon.png"]