name: 'Deploy 🚀'

on:
  push:
    tags:
      - '*.*.*'

env:
  GH_TOKEN: ${{ github.token }}
  NDK_VERSION: "27.2.12479018"
  APP_ENV: "production"

jobs:
  deploy:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: write
      discussions: write
    strategy:
      fail-fast: false
      matrix:
        include:
        # Windows
          - os: 'windows-2025'
            target: 'x86_64-pc-windows-msvc'
            name: 'Windows x86_64 🪟'
            platform: desktop
          - os: 'windows-2025'
            target: 'aarch64-pc-windows-msvc'
            name: 'Windows ARM64 🪟'
            platform: desktop
          # MacOS
          - os: 'macos-15'
            target: 'aarch64-apple-darwin'
            name: 'MacOS ARM64 🍏'
            platform: desktop
          - os: 'macos-15'
            target: 'x86_64-apple-darwin'
            name: 'MacOS x86_64 🍏'
            platform: desktop
          # Linux
          - os: 'ubuntu-24.04'
            target: 'x86_64-unknown-linux-gnu'
            name: 'Linux x86_64 🐧'
            platform: desktop
          - os: 'ubuntu-24.04-arm'
            target: 'aarch64-unknown-linux-gnu'
            name: 'Linux ARM64 🐧'
            platform: desktop
          # Android
          - os: 'macos-15'
            target: 'aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android'
            name: 'Android 🤖'
            platform: android
          # iOS
          - os: 'macos-15'
            target: 'aarch64-apple-ios aarch64-apple-ios-sim'
            name: 'iOS 📱'
            platform: ios
          # Web
          - os: 'ubuntu-24.04'
            target: ''
            name: 'Web 🌐'
            platform: web
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set version 📝
        shell: bash
        env:
          RELEASE_TAG: ${{ github.ref_name }}
        run: |
          mv Cargo.toml Cargo.toml.orig
          sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.orig >Cargo.toml

      - name: Setup Rust Targets 🦀
        if: ${{ matrix.platform != 'web'}}
        run: rustup target add ${{ matrix.target }}

      - name: Setup Java ☕
        if: ${{ matrix.platform == 'android'}}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Android 🤖
        if: ${{ matrix.platform == 'android'}}
        uses: android-actions/setup-android@v3

      - name: Install Cargo Binstall 🛠️
        uses: cargo-bins/cargo-binstall@main

      - name: Setup Dependencies & Configs 🛠️
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-24.04" || "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
            sudo apt update -y && sudo apt install build-essential libwebkit2gtk-4.1-dev libxdo-dev libayatana-appindicator3-dev librsvg2-dev libglib2.0-dev -y
          fi

          case "${{ matrix.os }}" in
            "ubuntu-24.04")
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
              mv tailwindcss-linux-x64 tailwindcss
              chmod +x tailwindcss
              ;;

            "ubuntu-24.04-arm")
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-arm64
              mv tailwindcss-linux-arm64 tailwindcss
              chmod +x tailwindcss
              ;;

            "macos-15")
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
              mv tailwindcss-macos-arm64 tailwindcss
              chmod +x tailwindcss
              ;;

            "windows-2025")
              curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-windows-x64
              mv tailwindcss-windows-x64 tailwindcss
              chmod +x tailwindcss
              ;;
          esac


          if [[ "${{ matrix.platform }}" == "web" ]]; then
            sed -i '/^\[web\.app\]$/a base_path = "dx-app"' Dioxus.toml
          elif [[ "${{ matrix.platform }}" == "android" ]]; then
            sdkmanager "ndk;$NDK_VERSION"
          fi

          ./tailwindcss -i ./input.css -o ./assets/tailwind.css
          cargo binstall dioxus-cli -y

      - name: Setup NASM for Windows 🛠️
        if: ${{ matrix.target == 'x86_64-pc-windows-msvc' }}
        uses: ilammy/setup-nasm@v1

      - name: Build & Deploy ${{ matrix.name }} 🚀
        shell: bash
        run: |
          if [[ "${{ matrix.platform }}" == "desktop" ]]; then
            dx bundle --release --platform ${{ matrix.platform }} --target ${{ matrix.target }} --features bundle
          elif [[ "${{ matrix.platform }}" == "android" ]]; then
            dx build --release --platform android
            dx bundle --release --platform android --features bundle
          else
            dx bundle --release --platform ${{ matrix.platform }} --features bundle
          fi

          if [[ "${{ matrix.platform }}" == "web" ]]; then
            cp target/dx/dx-app/release/web/public/index.html target/dx/dx-app/release/web/public/404.html
          fi

      - name: Upload Github Pages 📤
        if: ${{ matrix.platform == 'web'}}
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/dx/dx-app/release/web/public/

      - name: Deploy Github Pages 🌐
        if: ${{ matrix.platform == 'web'}}
        id: deployment
        uses: actions/deploy-pages@v4


      - name: Upload Artifacts 📦
        if: ${{ matrix.platform != 'web'}}
        shell: bash
        run: |
          if [[ "${{ matrix.name }}" == "Windows x86_64 🪟" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/windows/bundle/msi/DxApp_${{ github.ref_name }}_x64_en-US.msi \
              target/dx/dx-app/bundle/windows/bundle/nsis/DxApp_${{ github.ref_name }}_x64-setup.exe

          elif [[ "${{ matrix.name }}" == "Windows ARM64 🪟" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/windows/bundle/msi/DxApp_${{ github.ref_name }}_arm64_en-US.msi \
              target/dx/dx-app/bundle/windows/bundle/nsis/DxApp_${{ github.ref_name }}_arm64-setup.exe

          elif [[ "${{ matrix.name }}" == "Linux x86_64 🐧" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/linux/bundle/deb/DxApp_${{ github.ref_name }}_amd64.deb \
              target/dx/dx-app/bundle/linux/bundle/rpm/DxApp-${{ github.ref_name }}-.x86_64.rpm \
              target/dx/dx-app/bundle/linux/bundle/appimage/DxApp_${{ github.ref_name }}_amd64.AppImage

          elif [[ "${{ matrix.name }}" == "Linux ARM64 🐧" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/linux/bundle/deb/DxApp_${{ github.ref_name }}_arm64.deb \
              target/dx/dx-app/bundle/linux/bundle/rpm/DxApp-${{ github.ref_name }}-.aarch64.rpm \
              target/dx/dx-app/bundle/linux/bundle/appimage/DxApp_${{ github.ref_name }}_aarch64.AppImage

          elif [[ "${{ matrix.name }}" == "MacOS x86_64 🍏" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/macos/bundle/dmg/DxApp_${{ github.ref_name }}_x64.dmg
          
          elif [[ "${{ matrix.name }}" == "MacOS ARM64 🍏" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/bundle/macos/bundle/dmg/DxApp_${{ github.ref_name }}_aarch64.dmg

          elif [[ "${{ matrix.name }}" == "iOS 📱" ]]; then
            zip -r ios.zip target/dx/dx-app/release/ios/DxApp.app
            gh release upload ${{ github.ref_name }} ios.zip

          elif [[ "${{ matrix.name }}" == "Android 🤖" ]]; then
            gh release upload ${{ github.ref_name }} target/dx/dx-app/release/android/app/app/build/outputs/apk/debug/app-debug.apk \
              target/dx/dx-app/release/android/app/app/build/outputs/bundle/release/DxApp-aarch64.aab
          fi
