name: 'Preview 🌐'

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Run Clippy 🧹
        run: cargo clippy --all-targets --all-features
  preview:
    enable: false #This is disabled since it overrides Github pages deployment
    name: Deploy Preview 🌐
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: development
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: preview
      cancel-in-progress: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Cache Rust 🦀
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Dependencies & Configs 🛠️
        shell: bash
        run: |
          sudo apt update -y && sudo apt install libwebkit2gtk-4.1-dev build-essential libssl-dev curl wget file libxdo-dev libayatana-appindicator3-dev librsvg2-dev -y
          sed -i '/^\[web\.app\]$/a base_path = "dx-app"' Dioxus.toml
          cargo install cargo-binstall
          cargo binstall dioxus-cli -y

      - name: Build & Deploy 🚀
        run: |
          dx bundle --release --platform web --features bundle
          cp target/dx/dx-app/release/web/public/index.html target/dx/dx-app/release/web/public/404.html

      - name: Upload web files as artifacts 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/dx/dx-app/release/web/public/

      - name: Deploy to Github Pages 🌐
        id: deployment
        uses: actions/deploy-pages@v4
