name: 'Test 🧪'

on:
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: macos-15
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Cache Rust 🦀
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Dependencies & Configs 🛠️
        shell: bash
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
          mv tailwindcss-macos-arm64 tailwindcss
          chmod +x tailwindcss
          ./tailwindcss -i ./input.css -o ./assets/tailwind.css

      - name: Run Clippy 🧹
        run: cargo clippy --all-targets --all-features
