name: 'Test 🧪'

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Run Clippy 🧹
        run: cargo clippy --all-targets --all-features
